image: alpine:latest

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - test-vulnerabilities
  - test
  - publish
  - upload-assets

include:
  - local: '/.gitlab-ci/Jobs/build_image.yml'
  - local: '/.gitlab-ci/Jobs/rules.yml'
  - local: '/.gitlab-ci/Jobs/test_vulnerabilities.yaml'
  - local: '/.gitlab-ci/Jobs/test_images.yaml'
  - local: '/.gitlab-ci/Jobs/publish.yaml'
  - local: '/.gitlab-ci/Jobs/docker-compose-file-upload.yml'
  - local: '/.gitlab-ci/Jobs/entrypoint_test.yml'
  - local: '/.gitlab-ci/Jobs/test_compose_files.yml'
