image: alpine:latest

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375/

stages:
  - scanning
  - build
  - test-vulnerabilities
  - test

include:
  - local: '/.gitlab-ci/Jobs/build_image.yml'
  - local: '/.gitlab-ci/Jobs/container_security_scan.yml'
  - local: '/.gitlab-ci/Jobs/test_vulnerabilities.yaml'
  - local: '/.gitlab-ci/Jobs/test_images.yaml'
