version: '3.4'
services:
  db:
    image: mysql:latest
    env_file:
      - env/mysql.env
    volumes:
      - database_volume:/var/lib/mysql
    ports:
      - 3306

  passbolt:
    image: gcr.io/passbolt-production/passbolt-api:2.0.0-rc2-debian
    depends_on:
      - db
    env_file:
      - env/passbolt.env
    volumes:
      - ./scripts/wait-for.sh:/usr/bin/wait-for.sh
    tmpfs:
      - /run
    command: ["/usr/bin/wait-for.sh", "db:3306", "--", "/docker-entrypoint.sh"]
    ports:
      - 80:80
      - 443:443

volumes:
  database_volume:
  gpg_volume:
  images_volume:
