version: '3.9'
services:

  db:
    image: mariadb:10.3
    container_name: db
    env_file:
      - env/mysql.env
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - database_volume:/var/lib/mysql
    ports:
      - "3306:3306"

  passbolt:
    build:
      context: ..
      dockerfile: dev/Dockerfile
      args:
        PECL_PASSBOLT_EXTENSIONS: "redis gnupg xdebug"
    container_name: passbolt
    depends_on:
      - db
      - mailhog
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - env/passbolt.env
    volumes:
      - ${PASSBOLT_API_PATH}:/var/www/passbolt
      - gpg_volume:/var/www/passbolt/config/gpg
      - images_volume:/var/www/passbolt/webroot/img/public/images
    command: ["/usr/bin/wait-for.sh", "db:3306", "--", "/docker-entrypoint.sh"]
    ports:
      - 80:80
      - 443:443

  ####################
  # Dev tools starts #
  ####################

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "9501:8080"
    depends_on:
      - db

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    restart: always
    # Mailhog logs are noisy so not logging it
    logging:
      driver: none
    ports:
      - "1025:1025" # SMTP server
      - "9502:8025" # Web UI

volumes:
  database_volume:
  gpg_volume:
  images_volume:
