.build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - |
      echo "********************************************"
      echo "Build details"
      echo "============================================"
      echo "Flavour ${PASSBOLT_FLAVOUR:-local}"
      echo "Commit  ${UPSTREAM_COMMIT_SHA:-latest}"
      echo "********************************************"
    - |
      /kaniko/executor --context $CI_PROJECT_DIR \
        --build-arg PASSBOLT_PKG="passbolt-$PASSBOLT_FLAVOUR-server" \
        --build-arg PASSBOLT_REPO_URL="https://download.passbolt.com/$PASSBOLT_FLAVOUR/debian" \
        --build-arg PASSBOLT_COMPONENT="$COMPONENT" \
        --dockerfile $CI_PROJECT_DIR/debian/Dockerfile \
        --destination $CI_REGISTRY_IMAGE:${PASSBOLT_FLAVOUR:-local}-$(date +%s)

build-docker:
  extends: .build
  variables:
    PASSBOLT_URL: "https://gitlab.com/api/v4/projects/$UPSTREAM_PROJECT_ID/repository/archive.tar.gz?sha=$UPSTREAM_COMMIT_SHA"
    PASSBOLT_CURL_HEADERS: "PRIVATE-TOKEN: $PRIVATE_TOKEN"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_BRANCH == "develop"'
      when: on_success
